title: Michael Bertolacci
email: m.bertolacci@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Research fellow at the University of Wollongong
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mbertolacci

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - code
  - Gemfile
  - Gemfile.lock
